---
- name: Install fzf
  ansible.builtin.command:
    cmd: brew install fzf
    creates: /opt/homebrew/bin/fzf

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    creates: "{{ ansible_user_dir }}/.oh-my-zsh"

- name: Deploy .zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"
    backup: true
