---
brew_taps:
  - hashicorp/tap
brew_taps_extra: []

brew_formulae:
  - ansible
  - ansible-lint
  - awscli
  - docker
  - ffmpeg
  - gh
  - glances
  - go
  - helm
  - kubernetes-cli
  - neovim
  - node
  - ponysay
  - poppler
  - rclone
  - tesseract
  - tmux
  - tmuxinator
brew_formulae_extra: []

brew_casks:
  - 1password
  - bettertouchtool
  - font-courier-prime
  - font-jetbrains-mono-nerd-font
  - google-chrome
  - iterm2
  - monitorcontrol
  - visual-studio-code

brew_casks_extra: []
