---
- name: Configure Mac laptop
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - role: brew
    - role: keyboard
    - role: iterm2
    - role: btt
    - role: shares
    - role: tmux
    - role: zsh
